export const CONTENT_PRESETS = [
  {
    id: 'innovation-forum',
    name: '혁신 포럼',
    eyebrow: 'GLOBAL FORUM',
    template: 'standard',
    accent: '#0e4a84',
    fields: {
      title: '2026 ERICA INNOVATION FORUM',
      subtitle: 'CONNECT · CREATE · INSPIRE',
      date: '2026-09-15',
      start: '14:00',
      end: '17:00',
      venue: '컨퍼런스홀 중강당',
      host: 'HANYANG UNIVERSITY ERICA',
      organizer: '',
      extra: 'GLOBAL IDEAS, REAL IMPACT',
    },
  },
  {
    id: 'industry-showcase',
    name: '성과공유회',
    eyebrow: '산학협력',
    template: 'blue',
    accent: '#3b91c9',
    fields: {
      title: 'ERICA 산학협력 성과공유회',
      subtitle: 'INDUSTRY · UNIVERSITY · RESEARCH',
      date: '2026-09-24',
      start: '14:00',
      end: '16:30',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '산학협력단',
      extra: '함께 만든 변화, 함께 여는 미래',
    },
  },
  {
    id: 'future-conference',
    name: '미래전략',
    eyebrow: 'REGIONAL INNOVATION',
    template: 'split',
    accent: '#18548b',
    fields: {
      title: '지역혁신 미래전략 컨퍼런스',
      subtitle: 'REGIONAL INNOVATION CONFERENCE 2026',
      date: '2026-10-15',
      start: '13:30',
      end: '17:00',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '지역혁신사업단',
      extra: '대학과 지역이 함께 만드는 지속가능한 성장',
    },
  },
  {
    id: 'mou-ceremony',
    name: '업무협약식',
    eyebrow: 'CEREMONY',
    template: 'ceremony',
    accent: '#ad8a57',
    fields: {
      title: 'ERICA 산학협력 업무협약식',
      subtitle: 'MOU SIGNING CEREMONY',
      date: '2026-11-05',
      start: '11:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '',
      extra: 'PARTNERSHIP FOR THE FUTURE',
    },
  },
];
