export const CONTENT_PRESETS = [
  {
    id: 'innovation-forum',
    name: '혁신 포럼',
    eyebrow: 'GLOBAL FORUM',
    template: 'standard',
    accent: '#0e4a84',
    fields: {
      title: '2026 ERICA INNOVATION FORUM',
      subtitle: 'CONNECT · CREATE · INSPIRE',
      date: '2026-09-15',
      start: '14:00',
      end: '17:00',
      venue: '컨퍼런스홀 중강당',
      host: 'HANYANG UNIVERSITY ERICA',
      organizer: '',
      extra: 'GLOBAL IDEAS, REAL IMPACT',
    },
  },
  {
    id: 'industry-showcase',
    name: '성과공유회',
    eyebrow: '산학협력',
    template: 'blue',
    accent: '#3b91c9',
    fields: {
      title: 'ERICA 산학협력 성과공유회',
      subtitle: 'INDUSTRY · UNIVERSITY · RESEARCH',
      date: '2026-09-24',
      start: '14:00',
      end: '16:30',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '산학협력단',
      extra: '함께 만든 변화, 함께 여는 미래',
    },
  },
  {
    id: 'future-conference',
    name: '미래전략',
    eyebrow: 'REGIONAL INNOVATION',
    template: 'split',
    accent: '#18548b',
    fields: {
      title: '지역혁신 미래전략 컨퍼런스',
      subtitle: 'REGIONAL INNOVATION CONFERENCE 2026',
      date: '2026-10-15',
      start: '13:30',
      end: '17:00',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '지역혁신사업단',
      extra: '대학과 지역이 함께 만드는 지속가능한 성장',
    },
  },
  {
    id: 'mou-ceremony',
    name: '업무협약식',
    eyebrow: 'CEREMONY',
    template: 'ceremony',
    accent: '#ad8a57',
    fields: {
      title: 'ERICA 산학협력 업무협약식',
      subtitle: 'MOU SIGNING CEREMONY',
      date: '2026-11-05',
      start: '11:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '한양대학교 ERICA',
      organizer: '',
      extra: 'PARTNERSHIP FOR THE FUTURE',
    },
  },
  {
    id: 'reference-official-line',
    name: '공식 하단 라인',
    eyebrow: '제공 예시 01',
    collection: 'reference',
    template: 'minimal',
    accent: '#064774',
    theme: 'light',
    asset: 'preset-backgrounds/official-line.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (소제목)',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
  {
    id: 'reference-corner-stripes',
    name: '코너 스트라이프',
    eyebrow: '제공 예시 02',
    collection: 'reference',
    template: 'minimal',
    accent: '#3c86bd',
    theme: 'light',
    asset: 'preset-backgrounds/corner-stripes.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (소제목)',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
  {
    id: 'reference-blue-wave',
    name: '블루 웨이브',
    eyebrow: '제공 예시 03',
    collection: 'reference',
    template: 'ceremony',
    accent: '#1395cf',
    theme: 'dark',
    asset: 'preset-backgrounds/blue-wave.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (소제목)',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
  {
    id: 'reference-lime-line',
    name: '라임 포인트 라인',
    eyebrow: '제공 예시 04',
    collection: 'reference',
    template: 'minimal',
    accent: '#9bc700',
    theme: 'light',
    asset: 'preset-backgrounds/lime-line.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: '',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
  {
    id: 'reference-navy-frame',
    name: '네이비 프레임',
    eyebrow: '제공 예시 05',
    collection: 'reference',
    template: 'minimal',
    accent: '#063f70',
    theme: 'light',
    asset: 'preset-backgrounds/navy-frame.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (소제목)',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
  {
    id: 'reference-deep-blue',
    name: '딥 블루 프레임',
    eyebrow: '제공 예시 06',
    collection: 'reference',
    template: 'ceremony',
    accent: '#2449dc',
    theme: 'dark',
    asset: 'preset-backgrounds/deep-blue.png',
    fields: {
      title: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (본문)',
      subtitle: 'ERICA 발전협력팀 컨퍼런스홀 LED 현수막 (소제목)',
      date: '2026-09-10',
      start: '10:00',
      end: '',
      venue: '컨퍼런스홀 중강당',
      host: '',
      organizer: '',
      extra: '',
    },
  },
];

const sharedReferenceLayout = {
  title: {
    x: 340,
    y: 67,
    width: 1900,
    height: 76,
    fontSize: 64,
    fontWeight: 700,
    textAlign: 'center',
  },
  subtitle: {
    x: 420,
    y: 27,
    width: 1740,
    height: 31,
    fontSize: 24,
    fontWeight: 700,
    textAlign: 'center',
  },
  date: {
    x: 620,
    y: 166,
    width: 570,
    height: 30,
    fontSize: 22,
    fontWeight: 700,
    textAlign: 'right',
  },
  venue: {
    x: 1370,
    y: 166,
    width: 650,
    height: 30,
    fontSize: 22,
    fontWeight: 700,
    textAlign: 'left',
  },
  host: { hidden: true },
  organizer: { hidden: true },
  logo: { hidden: true },
  extra: { hidden: true },
};

for (const preset of CONTENT_PRESETS.filter(
  (item) => item.collection === 'reference',
)) {
  const color = preset.theme === 'dark' ? '#ffffff' : '#003f65';
  preset.layout = Object.fromEntries(
    Object.entries(sharedReferenceLayout).map(([id, value]) => [
      id,
      {
        ...value,
        ...(['title', 'subtitle', 'date', 'venue'].includes(id)
          ? { color }
          : {}),
      },
    ]),
  );
  if (!preset.fields.subtitle) {
    preset.layout.title = { ...preset.layout.title, y: 53 };
    preset.layout.date = { ...preset.layout.date, y: 157 };
    preset.layout.venue = { ...preset.layout.venue, y: 157 };
  }
}
